"""Setup env file management — parse, write, sections."""

from __future__ import annotations

import datetime
import os
import re
import shutil
from pathlib import Path

from .setup_ui import bold, green, yellow, red, dim, prompt_yes_no

# ---------------------------------------------------------------------------
# Env file sections
# ---------------------------------------------------------------------------

_ENV_SECTIONS = [
    ("# Core", ["CURSOR_API_KEY", "CURSOR_API_URL", "CODE_AGENTS_HTTP_ONLY",
                "CODE_AGENTS_BACKEND", "CODE_AGENTS_CLAUDE_CLI_MODEL",
                "ANTHROPIC_API_KEY"]),
    ("# Server", ["HOST", "PORT", "LOG_LEVEL", "CODE_AGENTS_PUBLIC_BASE_URL", "OPEN_WEBUI_PUBLIC_URL"]),
    ("# Target Repository", ["TARGET_REPO_PATH", "TARGET_REPO_REMOTE"]),
    ("# Testing", ["TARGET_TEST_COMMAND", "TARGET_COVERAGE_THRESHOLD"]),
    ("# Jenkins", ["JENKINS_URL", "JENKINS_USERNAME", "JENKINS_API_TOKEN", "JENKINS_BUILD_JOB", "JENKINS_DEPLOY_JOB"]),
    ("# ArgoCD", ["ARGOCD_URL", "ARGOCD_AUTH_TOKEN", "ARGOCD_APP_NAME", "ARGOCD_VERIFY_SSL"]),
    ("# Elasticsearch", ["ELASTICSEARCH_URL", "ELASTICSEARCH_CLOUD_ID", "ELASTICSEARCH_API_KEY",
                         "ELASTICSEARCH_USERNAME", "ELASTICSEARCH_PASSWORD",
                         "ELASTICSEARCH_CA_CERTS", "ELASTICSEARCH_VERIFY_SSL"]),
    ("# Atlassian OAuth", ["ATLASSIAN_OAUTH_CLIENT_ID", "ATLASSIAN_OAUTH_CLIENT_SECRET",
                           "ATLASSIAN_OAUTH_SCOPES", "ATLASSIAN_CLOUD_SITE_URL",
                           "ATLASSIAN_OAUTH_SUCCESS_REDIRECT", "CODE_AGENTS_HTTPS_VERIFY"]),
    ("# Redash", ["REDASH_BASE_URL", "REDASH_API_KEY", "REDASH_USERNAME", "REDASH_PASSWORD"]),
]


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse a .env file into a dict."""
    result = {}
    if not path.exists() or not path.is_file():
        return result
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        match = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)', line)
        if match:
            key = match.group(1)
            value = match.group(2).strip()
            if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
                value = value[1:-1]
            result[key] = value
    return result


def _write_env_to_path(env_path: Path, env_vars: dict[str, str], label: str) -> None:
    """Write env vars to a specific path with section grouping."""
    env_path.parent.mkdir(parents=True, exist_ok=True)

    if env_path.exists():
        existing = parse_env_file(env_path)
        existing_count = len(existing)
        print(f"  Found existing {label} with {existing_count} configured variables.")
        print(f"    [O] Overwrite with new values")
        print(f"    [M] Merge (keep existing, add new)")
        print(f"    [B] Backup existing, then overwrite")
        print(f"    [C] Cancel")
        while True:
            try:
                choice = input("  Choice [M]: ").strip().lower() or "m"
            except EOFError:
                choice = "c"
            if choice in ("o", "m", "b", "c"):
                break
            print(red("    Enter O, M, B, or C."))

        if choice == "c":
            print(yellow(f"  Skipped — {label} not modified."))
            return
        if choice == "b":
            ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            backup = env_path.with_suffix(f".backup.{ts}")
            shutil.copy2(env_path, backup)
            print(green(f"  ✓ Backed up to {backup}"))
        if choice == "m":
            merged = dict(existing)
            added = 0
            for k, v in env_vars.items():
                if k not in merged:
                    merged[k] = v
                    added += 1
            env_vars = merged
            print(dim(f"    Merged: {added} new keys added, {existing_count} existing kept."))

    lines = [f"# Generated by code-agents init — {label}", ""]
    written_keys: set[str] = set()

    for section_comment, keys in _ENV_SECTIONS:
        section_vars = {k: env_vars[k] for k in keys if k in env_vars}
        if section_vars:
            lines.append(section_comment)
            for k, v in section_vars.items():
                if " " in v:
                    lines.append(f'{k}="{v}"')
                else:
                    lines.append(f"{k}={v}")
                written_keys.add(k)
            lines.append("")

    remaining = {k: v for k, v in env_vars.items() if k not in written_keys}
    if remaining:
        lines.append("# Other")
        for k, v in remaining.items():
            if " " in v:
                lines.append(f'{k}="{v}"')
            else:
                lines.append(f"{k}={v}")
        lines.append("")

    content = "\n".join(lines)
    env_path.write_text(content)

    try:
        os.chmod(env_path, 0o600)
    except OSError:
        pass

    count = len(env_vars)
    print(green(f"  ✓ {label} written ({count} variables, permissions: 600)"))
    print(f"    {dim(str(env_path))}")
    print()


def write_env_file(env_vars: dict[str, str]) -> None:
    """Write env vars to centralized global + per-repo config files."""
    from .env_loader import GLOBAL_ENV_PATH, PER_REPO_FILENAME, split_vars

    global_vars, repo_vars = split_vars(env_vars)

    if global_vars:
        print(bold("  Writing global config (API keys, server, integrations):"))
        _write_env_to_path(GLOBAL_ENV_PATH, global_vars, "global config")

    if repo_vars:
        print(bold("  Writing per-repo config (Jenkins, ArgoCD, testing):"))
        _write_env_to_path(Path(PER_REPO_FILENAME), repo_vars, "repo config")
